apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: gerenciador-produtos
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30050
  selector:
    service: webapi