version: '3.4'

services:
  favodemel.catalogo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogoDbConnection=Server=local-mssql,1433;Database=CatalogoDb;User Id=sa;Password=P@ssw0rd
      - RABBITMQ__URL=local-rabbitmq
      - RABBITMQ__USUARIO=guest
      - RABBITMQ__SENHA=guest
      - RABBITMQ__VHOST=/
      - RABBITMQ__QUEUE=favoDeMelQueue
      - RABBITMQ__RETRY=5
    ports:
      - "5110:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
    networks:
      - favodemel-network

  favodemel.venda.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - VendaDbConnection=Server=local-mssql,1433;Database=VendaDb;User Id=sa;Password=P@ssw0rd
      - RABBITMQ__URL=local-rabbitmq
      - RABBITMQ__USUARIO=guest
      - RABBITMQ__SENHA=guest
      - RABBITMQ__VHOST=/
      - RABBITMQ__QUEUE=favoDeMelQueue
      - RABBITMQ__RETRY=5
    ports:
      - "5120:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
    networks:
      - favodemel-network

  favodemel.presentation.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MICROSERVICES__VENDA_BASE_URI=http://venda-api
      - MICROSERVICES__CATALOGO_BASE_URI=http://catalogo-api
      - IDENTITYPROVIDER__AUTHORITYURI=http://identity-api
    ports:
      - "5130:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
    networks:
      - favodemel-network

  favodemel.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDbConnection=Server=local-mssql,1433;Database=IdentityDb;User Id=sa;Password=P@ssw0rd
      - AppSettings__Secret=MEUSEGREDOSUPERSECRETO
      - AppSettings__ExpiracaoHoras=2
      - AppSettings__Emissor=FavoMel.Identity
      - AppSettings__ValidoEm=http://localhost
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - favodemel-network

  favodemel.webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5150:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - favodemel-network

  favodemel.healthcheck-ui:
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__Loglevel__Microsoft=Warning
      - Logging__LogLevel__HealthChecks=Debug
      - ui_path=/
      - ui_api_path=/api
      - ui_webhooks_path=/webhooks
      - HealthChecksUI__HealthChecks__0__Name=API Status 
      - HealthChecksUI__HealthChecks__0__Uri=http://webstatus-api/healthz
      - HealthChecksUI__HealthChecks__1__Name=API Catalogo
      - HealthChecksUI__HealthChecks__1__Uri=http://catalogo-api/healthz
      - HealthChecksUI__HealthChecks__2__Name=API Vendas
      - HealthChecksUI__HealthChecks__2__Uri=http://venda-api/healthz
      - HealthChecksUI__HealthChecks__3__Name=API Identity
      - HealthChecksUI__HealthChecks__3__Uri=http://identity-api/healthz
    ports:
      - "5160:80"
    networks:
      - favodemel-network

  favodemel.rabbitmq:
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - favodemel-network

  favodemel.sqlserver:
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "P@ssw0rd"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - '11433:1433'    
    expose:
      - 1433
    networks:
      - favodemel-network

  favodemel.elasticsearch:
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - favodemel-network

  favodemel.kibana:
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - favodemel-network

networks:
  favodemel-network:
    driver: bridge    

volumes:
  mssql-data:
  elasticsearch-data: