apiVersion: v1
kind: Service
metadata:
  name: database-mongo
  labels:
    app: database-gerenciador-produtos
    service: database-mongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
  selector:
    service: database-mongo